version: "3.4"

services:
  logs:
    container_name: 'logs'
    build: '$GOPATH/src/telegram_boxes/services/logs'
    ports:
      - ${LOGS_PORT}:${LOGS_PORT}
    volumes:
      - /Users/sparrowganz/go/src/telegram_boxes/logs:${LOGS_PATH}
    restart: always
    environment:
      - APP_MODE=${APP_MODE}
      - LOGS_PORT=${LOGS_PORT}
      - LOGS_PATH=${LOGS_PATH}