version: "3.4"

services:
  admin:
    container_name: 'admin'
    build: '$GOPATH/src/telegram_boxes/services/admin'
    restart: always
    depends_on:
      - core
    environment:
      - APP_MODE=${APP_MODE}

      - ADMIN_PORT=${ADMIN_PORT}

      - ADMINS=${ADMINS}
      - ADMIN_TOKEN=${ADMIN_TOKEN}

      - LOGS_HOST=${LOGS_HOST}
      - LOGS_PORT=${LOGS_PORT}

      - CORE_HOST=${CORE_HOST}
      - CORE_PORT=${CORE_PORT}

  core:
    container_name: "core"
    build: '$GOPATH/src/telegram_boxes/services/core'
    ports:
      - ${CORE_PORT}:${CORE_PORT}
    restart: always
    depends_on:
      - logs
      - database
    environment:
      - APP_MODE=${APP_MODE}
      - CORE_PORT=${CORE_PORT}

      - LOGS_PORT=${LOGS_PORT}
      - LOGS_HOST=${LOGS_HOST}
      - ADMIN_HOST=${ADMIN_HOST}
      - ADMIN_PORT=${ADMIN_PORT}

      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_MECHANISM=${MONGO_MECHANISM}

  logs:
    container_name: 'logs'
    build: '$GOPATH/src/telegram_boxes/services/logs'
    ports:
      - ${LOGS_PORT}:${LOGS_PORT}
    volumes:
      - /Users/sparrowganz/go/src/telegram_boxes/logs:${LOGS_PATH}
    restart: always
    environment:
      - APP_MODE=${APP_MODE}
      - LOGS_PORT=${LOGS_PORT}
      - LOGS_PATH=${LOGS_PATH}

  database:
    container_name: 'database_CORE'
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/db:/bitnami/mongodb/data/db
    ports:
      - ${MONGO_PORT}:27017