version: "3.4"

services:
  box:
    container_name: "box_TEST"
    build: '$GOPATH/src/telegram_boxes/services/box'
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - database
    volumes:
      - ${LOCAL_PATH_DIR}:${BOX_PATH_DIR}
    environment:
      - APP_MODE=${APP_MODE}
      - APP_IP=${APP_IP}
      - APP_PORT=${APP_PORT}
      - BOX_PATH_DIR=${BOX_PATH_DIR}
      - NAME_CONFIG_FILE=${NAME_CONFIG_FILE}
      - BOT_USERNAME=${BOT_USERNAME}
      - TOKEN=${TOKEN}

      - LOGS_HOST=${LOGS_HOST}
      - LOGS_PORT=${LOGS_PORT}

      - CORE_HOST=${CORE_HOST}
      - CORE_PORT=${CORE_PORT}

      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_MECHANISM=${MONGO_MECHANISM}

  database:
    container_name: 'database_TEST'
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/db:/bitnami/mongodb/data/db
    ports:
      - ${MONGO_PORT}:27017
