version: "3.4"

services:
  box:
    container_name: "box_"+${BOX_NAME}
    build: '../../services/box'
    ports:
      - ${APP_PORT}:4000
    restart: always
    environment:
      - APP_MODE=${APP_MODE}

  database:
    container_name: 'database_'+${BOX_NAME}
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./data/models:/bitnami/mongodb/data/models
    ports:
      - ${MONGO_PORT}:27017
