// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/logs/protobuf/logs.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//----------------------------------------------------------------------------------------------------------------------
//  Access Log
//----------------------------------------------------------------------------------------------------------------------
type AccessLogRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ServerName           string   `protobuf:"bytes,3,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Duration             string   `protobuf:"bytes,5,opt,name=Duration,proto3" json:"Duration,omitempty"`
	User                 string   `protobuf:"bytes,6,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessLogRequest) Reset()         { *m = AccessLogRequest{} }
func (m *AccessLogRequest) String() string { return proto.CompactTextString(m) }
func (*AccessLogRequest) ProtoMessage()    {}
func (*AccessLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{0}
}

func (m *AccessLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessLogRequest.Unmarshal(m, b)
}
func (m *AccessLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessLogRequest.Marshal(b, m, deterministic)
}
func (m *AccessLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessLogRequest.Merge(m, src)
}
func (m *AccessLogRequest) XXX_Size() int {
	return xxx_messageInfo_AccessLogRequest.Size(m)
}
func (m *AccessLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccessLogRequest proto.InternalMessageInfo

func (m *AccessLogRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AccessLogRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *AccessLogRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AccessLogRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AccessLogRequest) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *AccessLogRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type AccessLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessLogResponse) Reset()         { *m = AccessLogResponse{} }
func (m *AccessLogResponse) String() string { return proto.CompactTextString(m) }
func (*AccessLogResponse) ProtoMessage()    {}
func (*AccessLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{1}
}

func (m *AccessLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessLogResponse.Unmarshal(m, b)
}
func (m *AccessLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessLogResponse.Marshal(b, m, deterministic)
}
func (m *AccessLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessLogResponse.Merge(m, src)
}
func (m *AccessLogResponse) XXX_Size() int {
	return xxx_messageInfo_AccessLogResponse.Size(m)
}
func (m *AccessLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccessLogResponse proto.InternalMessageInfo

type ErrorLogRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorLogRequest) Reset()         { *m = ErrorLogRequest{} }
func (m *ErrorLogRequest) String() string { return proto.CompactTextString(m) }
func (*ErrorLogRequest) ProtoMessage()    {}
func (*ErrorLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{2}
}

func (m *ErrorLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorLogRequest.Unmarshal(m, b)
}
func (m *ErrorLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorLogRequest.Marshal(b, m, deterministic)
}
func (m *ErrorLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorLogRequest.Merge(m, src)
}
func (m *ErrorLogRequest) XXX_Size() int {
	return xxx_messageInfo_ErrorLogRequest.Size(m)
}
func (m *ErrorLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorLogRequest proto.InternalMessageInfo

func (m *ErrorLogRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ErrorLogRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *ErrorLogRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ErrorLogRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ErrorLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorLogResponse) Reset()         { *m = ErrorLogResponse{} }
func (m *ErrorLogResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorLogResponse) ProtoMessage()    {}
func (*ErrorLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{3}
}

func (m *ErrorLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorLogResponse.Unmarshal(m, b)
}
func (m *ErrorLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorLogResponse.Marshal(b, m, deterministic)
}
func (m *ErrorLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorLogResponse.Merge(m, src)
}
func (m *ErrorLogResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorLogResponse.Size(m)
}
func (m *ErrorLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorLogResponse proto.InternalMessageInfo

type SystemLogRequest struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemLogRequest) Reset()         { *m = SystemLogRequest{} }
func (m *SystemLogRequest) String() string { return proto.CompactTextString(m) }
func (*SystemLogRequest) ProtoMessage()    {}
func (*SystemLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{4}
}

func (m *SystemLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemLogRequest.Unmarshal(m, b)
}
func (m *SystemLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemLogRequest.Marshal(b, m, deterministic)
}
func (m *SystemLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemLogRequest.Merge(m, src)
}
func (m *SystemLogRequest) XXX_Size() int {
	return xxx_messageInfo_SystemLogRequest.Size(m)
}
func (m *SystemLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemLogRequest proto.InternalMessageInfo

func (m *SystemLogRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *SystemLogRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SystemLogRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SystemLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemLogResponse) Reset()         { *m = SystemLogResponse{} }
func (m *SystemLogResponse) String() string { return proto.CompactTextString(m) }
func (*SystemLogResponse) ProtoMessage()    {}
func (*SystemLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f6cebb36956a2f2, []int{5}
}

func (m *SystemLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemLogResponse.Unmarshal(m, b)
}
func (m *SystemLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemLogResponse.Marshal(b, m, deterministic)
}
func (m *SystemLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemLogResponse.Merge(m, src)
}
func (m *SystemLogResponse) XXX_Size() int {
	return xxx_messageInfo_SystemLogResponse.Size(m)
}
func (m *SystemLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemLogResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccessLogRequest)(nil), "protobuf.AccessLogRequest")
	proto.RegisterType((*AccessLogResponse)(nil), "protobuf.AccessLogResponse")
	proto.RegisterType((*ErrorLogRequest)(nil), "protobuf.ErrorLogRequest")
	proto.RegisterType((*ErrorLogResponse)(nil), "protobuf.ErrorLogResponse")
	proto.RegisterType((*SystemLogRequest)(nil), "protobuf.SystemLogRequest")
	proto.RegisterType((*SystemLogResponse)(nil), "protobuf.SystemLogResponse")
}

func init() {
	proto.RegisterFile("services/logs/protobuf/logs.proto", fileDescriptor_4f6cebb36956a2f2)
}

var fileDescriptor_4f6cebb36956a2f2 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcb, 0x4e, 0x32, 0x41,
	0x10, 0x85, 0x69, 0x2e, 0x13, 0xa6, 0x36, 0x3f, 0x7f, 0x69, 0x4c, 0x3b, 0x1a, 0x83, 0xb3, 0x62,
	0x05, 0x89, 0x3e, 0x81, 0x11, 0x49, 0x4c, 0xd0, 0xc5, 0xa0, 0x1b, 0x77, 0x03, 0x94, 0x23, 0x89,
	0xd0, 0xd8, 0xdd, 0x90, 0xf0, 0x4e, 0xbe, 0x92, 0xef, 0x62, 0x28, 0xe6, 0xd2, 0x0e, 0xb8, 0x71,
	0x57, 0x55, 0xa7, 0xd2, 0xe7, 0x3b, 0xd5, 0x70, 0x69, 0x48, 0xaf, 0x67, 0x13, 0x32, 0xbd, 0x77,
	0x95, 0x98, 0xde, 0x52, 0x2b, 0xab, 0xc6, 0xab, 0x57, 0xee, 0xba, 0xdc, 0x61, 0x33, 0x1b, 0x86,
	0x9f, 0x02, 0x5a, 0x37, 0x93, 0x09, 0x19, 0x33, 0x54, 0x49, 0x44, 0x1f, 0x2b, 0x32, 0x16, 0xcf,
	0xc1, 0x4f, 0xcb, 0xfb, 0xa9, 0x14, 0x6d, 0xd1, 0xf1, 0xa3, 0x62, 0x80, 0x17, 0x00, 0x23, 0xd2,
	0x6b, 0xd2, 0x8f, 0xf1, 0x9c, 0x64, 0x8d, 0x65, 0x67, 0x82, 0x27, 0xe0, 0x3d, 0x90, 0x7d, 0x53,
	0x53, 0x59, 0x65, 0x2d, 0xed, 0x10, 0xa1, 0xfe, 0x34, 0x9b, 0x93, 0xac, 0xb7, 0x45, 0xa7, 0x16,
	0x71, 0x8d, 0x01, 0x34, 0xfb, 0x2b, 0x1d, 0xdb, 0x99, 0x5a, 0xc8, 0x06, 0x6f, 0xe7, 0xfd, 0x76,
	0xff, 0xd9, 0x90, 0x96, 0x1e, 0xcf, 0xb9, 0x0e, 0x8f, 0xe0, 0xbf, 0x43, 0x6b, 0x96, 0x6a, 0x61,
	0x28, 0xdc, 0xc0, 0xbf, 0x3b, 0xad, 0x95, 0xfe, 0x63, 0x82, 0xea, 0x5e, 0x82, 0x8c, 0xb4, 0xe6,
	0x90, 0x1e, 0x43, 0x83, 0x4d, 0x18, 0xdf, 0x8f, 0x76, 0x4d, 0x88, 0xd0, 0x2a, 0xac, 0x53, 0x9c,
	0x17, 0x68, 0x8d, 0x36, 0xc6, 0xd2, 0xdc, 0xe1, 0xf9, 0xe9, 0x28, 0x7e, 0x75, 0xac, 0x3a, 0x8e,
	0x08, 0xf5, 0x7e, 0x6c, 0xe3, 0xf4, 0xc2, 0x5c, 0x6f, 0xf3, 0x3b, 0x6f, 0xef, 0x0c, 0xaf, 0xbe,
	0x04, 0x78, 0x43, 0x95, 0x24, 0xa4, 0x71, 0x00, 0x7e, 0x7e, 0x1f, 0x0c, 0xba, 0xd9, 0x37, 0x77,
	0xcb, 0x5f, 0x1c, 0x9c, 0x1d, 0xd4, 0xd2, 0x04, 0x15, 0xbc, 0x85, 0x66, 0x96, 0x0b, 0x4f, 0x8b,
	0xd5, 0xd2, 0x99, 0x83, 0xe0, 0x90, 0x94, 0x3f, 0x32, 0x00, 0x3f, 0x87, 0x75, 0x61, 0xca, 0xd7,
	0x71, 0x61, 0xf6, 0xd2, 0x85, 0x95, 0xb1, 0xc7, 0xea, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xad, 0xe7, 0xe2, 0x47, 0xd9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	//отправка сообщения
	AccessLog(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error)
	ErrorLog(ctx context.Context, in *ErrorLogRequest, opts ...grpc.CallOption) (*ErrorLogResponse, error)
	SystemLog(ctx context.Context, in *SystemLogRequest, opts ...grpc.CallOption) (*SystemLogResponse, error)
}

type loggerClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerClient(cc grpc.ClientConnInterface) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) AccessLog(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error) {
	out := new(AccessLogResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Logger/AccessLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) ErrorLog(ctx context.Context, in *ErrorLogRequest, opts ...grpc.CallOption) (*ErrorLogResponse, error) {
	out := new(ErrorLogResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Logger/ErrorLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) SystemLog(ctx context.Context, in *SystemLogRequest, opts ...grpc.CallOption) (*SystemLogResponse, error) {
	out := new(SystemLogResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Logger/SystemLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	//отправка сообщения
	AccessLog(context.Context, *AccessLogRequest) (*AccessLogResponse, error)
	ErrorLog(context.Context, *ErrorLogRequest) (*ErrorLogResponse, error)
	SystemLog(context.Context, *SystemLogRequest) (*SystemLogResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) AccessLog(ctx context.Context, req *AccessLogRequest) (*AccessLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessLog not implemented")
}
func (*UnimplementedLoggerServer) ErrorLog(ctx context.Context, req *ErrorLogRequest) (*ErrorLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ErrorLog not implemented")
}
func (*UnimplementedLoggerServer) SystemLog(ctx context.Context, req *SystemLogRequest) (*SystemLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemLog not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_AccessLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).AccessLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Logger/AccessLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).AccessLog(ctx, req.(*AccessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_ErrorLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).ErrorLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Logger/ErrorLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).ErrorLog(ctx, req.(*ErrorLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_SystemLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).SystemLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Logger/SystemLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).SystemLog(ctx, req.(*SystemLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccessLog",
			Handler:    _Logger_AccessLog_Handler,
		},
		{
			MethodName: "ErrorLog",
			Handler:    _Logger_ErrorLog_Handler,
		},
		{
			MethodName: "SystemLog",
			Handler:    _Logger_SystemLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/logs/protobuf/logs.proto",
}
