// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: services/core/protobuf/outputs.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_services_core_protobuf_outputs_proto protoreflect.FileDescriptor

var file_services_core_protobuf_outputs_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x32, 0x09, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_services_core_protobuf_outputs_proto_goTypes = []interface{}{}
var file_services_core_protobuf_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_core_protobuf_outputs_proto_init() }
func file_services_core_protobuf_outputs_proto_init() {
	if File_services_core_protobuf_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_core_protobuf_outputs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_core_protobuf_outputs_proto_goTypes,
		DependencyIndexes: file_services_core_protobuf_outputs_proto_depIdxs,
	}.Build()
	File_services_core_protobuf_outputs_proto = out.File
	file_services_core_protobuf_outputs_proto_rawDesc = nil
	file_services_core_protobuf_outputs_proto_goTypes = nil
	file_services_core_protobuf_outputs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OutputsClient is the client API for Outputs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OutputsClient interface {
}

type outputsClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputsClient(cc grpc.ClientConnInterface) OutputsClient {
	return &outputsClient{cc}
}

// OutputsServer is the server API for Outputs service.
type OutputsServer interface {
}

// UnimplementedOutputsServer can be embedded to have forward compatible implementations.
type UnimplementedOutputsServer struct {
}

func RegisterOutputsServer(s *grpc.Server, srv OutputsServer) {
	s.RegisterService(&_Outputs_serviceDesc, srv)
}

var _Outputs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Outputs",
	HandlerType: (*OutputsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "services/core/protobuf/outputs.proto",
}
