// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: services/core/protobuf/servers.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_OK         Status = 0
	Status_Recovering Status = 1
	Status_Fatal      Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "Recovering",
		2: "Fatal",
	}
	Status_value = map[string]int32{
		"OK":         0,
		"Recovering": 1,
		"Fatal":      2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_services_core_protobuf_servers_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_services_core_protobuf_servers_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{0}
}

//----------------------------------------------------------------------------------------------------------------------
//  Init box
//----------------------------------------------------------------------------------------------------------------------
type InitBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *InitBoxRequest) Reset() {
	*x = InitBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBoxRequest) ProtoMessage() {}

func (x *InitBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBoxRequest.ProtoReflect.Descriptor instead.
func (*InitBoxRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{0}
}

func (x *InitBoxRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type InitBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *InitBoxResponse) Reset() {
	*x = InitBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBoxResponse) ProtoMessage() {}

func (x *InitBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBoxResponse.ProtoReflect.Descriptor instead.
func (*InitBoxResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{1}
}

func (x *InitBoxResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

//----------------------------------------------------------------------------------------------------------------------
//  Send Error
//----------------------------------------------------------------------------------------------------------------------
type SendErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=protobuf.Status" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *SendErrorRequest) Reset() {
	*x = SendErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendErrorRequest) ProtoMessage() {}

func (x *SendErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendErrorRequest.ProtoReflect.Descriptor instead.
func (*SendErrorRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{2}
}

func (x *SendErrorRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *SendErrorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendErrorResponse) Reset() {
	*x = SendErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendErrorResponse) ProtoMessage() {}

func (x *SendErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendErrorResponse.ProtoReflect.Descriptor instead.
func (*SendErrorResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{3}
}

var File_services_core_protobuf_servers_proto protoreflect.FileDescriptor

var file_services_core_protobuf_servers_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x22, 0x2c, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21,
	0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x2b, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x46, 0x61, 0x74, 0x61, 0x6c, 0x10, 0x02, 0x32, 0x93, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a,
	0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_core_protobuf_servers_proto_rawDescOnce sync.Once
	file_services_core_protobuf_servers_proto_rawDescData = file_services_core_protobuf_servers_proto_rawDesc
)

func file_services_core_protobuf_servers_proto_rawDescGZIP() []byte {
	file_services_core_protobuf_servers_proto_rawDescOnce.Do(func() {
		file_services_core_protobuf_servers_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_core_protobuf_servers_proto_rawDescData)
	})
	return file_services_core_protobuf_servers_proto_rawDescData
}

var file_services_core_protobuf_servers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_core_protobuf_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_core_protobuf_servers_proto_goTypes = []interface{}{
	(Status)(0),               // 0: protobuf.Status
	(*InitBoxRequest)(nil),    // 1: protobuf.InitBoxRequest
	(*InitBoxResponse)(nil),   // 2: protobuf.InitBoxResponse
	(*SendErrorRequest)(nil),  // 3: protobuf.SendErrorRequest
	(*SendErrorResponse)(nil), // 4: protobuf.SendErrorResponse
}
var file_services_core_protobuf_servers_proto_depIdxs = []int32{
	0, // 0: protobuf.SendErrorRequest.status:type_name -> protobuf.Status
	1, // 1: protobuf.Servers.InitBox:input_type -> protobuf.InitBoxRequest
	3, // 2: protobuf.Servers.SendError:input_type -> protobuf.SendErrorRequest
	2, // 3: protobuf.Servers.InitBox:output_type -> protobuf.InitBoxResponse
	4, // 4: protobuf.Servers.SendError:output_type -> protobuf.SendErrorResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_core_protobuf_servers_proto_init() }
func file_services_core_protobuf_servers_proto_init() {
	if File_services_core_protobuf_servers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_core_protobuf_servers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_core_protobuf_servers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_core_protobuf_servers_proto_goTypes,
		DependencyIndexes: file_services_core_protobuf_servers_proto_depIdxs,
		EnumInfos:         file_services_core_protobuf_servers_proto_enumTypes,
		MessageInfos:      file_services_core_protobuf_servers_proto_msgTypes,
	}.Build()
	File_services_core_protobuf_servers_proto = out.File
	file_services_core_protobuf_servers_proto_rawDesc = nil
	file_services_core_protobuf_servers_proto_goTypes = nil
	file_services_core_protobuf_servers_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServersClient is the client API for Servers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServersClient interface {
	InitBox(ctx context.Context, in *InitBoxRequest, opts ...grpc.CallOption) (*InitBoxResponse, error)
	SendError(ctx context.Context, in *SendErrorRequest, opts ...grpc.CallOption) (*SendErrorResponse, error)
}

type serversClient struct {
	cc grpc.ClientConnInterface
}

func NewServersClient(cc grpc.ClientConnInterface) ServersClient {
	return &serversClient{cc}
}

func (c *serversClient) InitBox(ctx context.Context, in *InitBoxRequest, opts ...grpc.CallOption) (*InitBoxResponse, error) {
	out := new(InitBoxResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/InitBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) SendError(ctx context.Context, in *SendErrorRequest, opts ...grpc.CallOption) (*SendErrorResponse, error) {
	out := new(SendErrorResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/SendError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServersServer is the server API for Servers service.
type ServersServer interface {
	InitBox(context.Context, *InitBoxRequest) (*InitBoxResponse, error)
	SendError(context.Context, *SendErrorRequest) (*SendErrorResponse, error)
}

// UnimplementedServersServer can be embedded to have forward compatible implementations.
type UnimplementedServersServer struct {
}

func (*UnimplementedServersServer) InitBox(context.Context, *InitBoxRequest) (*InitBoxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBox not implemented")
}
func (*UnimplementedServersServer) SendError(context.Context, *SendErrorRequest) (*SendErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendError not implemented")
}

func RegisterServersServer(s *grpc.Server, srv ServersServer) {
	s.RegisterService(&_Servers_serviceDesc, srv)
}

func _Servers_InitBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).InitBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/InitBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).InitBox(ctx, req.(*InitBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_SendError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).SendError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/SendError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).SendError(ctx, req.(*SendErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Servers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Servers",
	HandlerType: (*ServersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitBox",
			Handler:    _Servers_InitBox_Handler,
		},
		{
			MethodName: "SendError",
			Handler:    _Servers_SendError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/core/protobuf/servers.proto",
}
