// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: services/core/protobuf/servers.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_OK         Status = 0
	Status_Recovering Status = 1
	Status_Fatal      Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "Recovering",
		2: "Fatal",
	}
	Status_value = map[string]int32{
		"OK":         0,
		"Recovering": 1,
		"Fatal":      2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_services_core_protobuf_servers_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_services_core_protobuf_servers_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{0}
}

type GetAllBroadcastsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllBroadcastsRequest) Reset() {
	*x = GetAllBroadcastsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBroadcastsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBroadcastsRequest) ProtoMessage() {}

func (x *GetAllBroadcastsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBroadcastsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBroadcastsRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{0}
}

type GetAllBroadcastsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats []*Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetAllBroadcastsResponse) Reset() {
	*x = GetAllBroadcastsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBroadcastsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBroadcastsResponse) ProtoMessage() {}

func (x *GetAllBroadcastsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBroadcastsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBroadcastsResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllBroadcastsResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetStatisticsBroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BroadcastID string `protobuf:"bytes,1,opt,name=broadcastID,proto3" json:"broadcastID,omitempty"`
}

func (x *GetStatisticsBroadcastRequest) Reset() {
	*x = GetStatisticsBroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsBroadcastRequest) ProtoMessage() {}

func (x *GetStatisticsBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsBroadcastRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatisticsBroadcastRequest) GetBroadcastID() string {
	if x != nil {
		return x.BroadcastID
	}
	return ""
}

type GetStatisticsBroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats []*Stat `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetStatisticsBroadcastResponse) Reset() {
	*x = GetStatisticsBroadcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsBroadcastResponse) ProtoMessage() {}

func (x *GetStatisticsBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsBroadcastResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatisticsBroadcastResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StopBroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BroadcastID string `protobuf:"bytes,1,opt,name=broadcastID,proto3" json:"broadcastID,omitempty"`
}

func (x *StopBroadcastRequest) Reset() {
	*x = StopBroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBroadcastRequest) ProtoMessage() {}

func (x *StopBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBroadcastRequest.ProtoReflect.Descriptor instead.
func (*StopBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{4}
}

func (x *StopBroadcastRequest) GetBroadcastID() string {
	if x != nil {
		return x.BroadcastID
	}
	return ""
}

type StopBroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopBroadcastResponse) Reset() {
	*x = StopBroadcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBroadcastResponse) ProtoMessage() {}

func (x *StopBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBroadcastResponse.ProtoReflect.Descriptor instead.
func (*StopBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{5}
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BotID       string `protobuf:"bytes,2,opt,name=botID,proto3" json:"botID,omitempty"`
	BotUsername string `protobuf:"bytes,3,opt,name=botUsername,proto3" json:"botUsername,omitempty"`
	Success     int64  `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Fail        int64  `protobuf:"varint,5,opt,name=fail,proto3" json:"fail,omitempty"`
	Time        int64  `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{6}
}

func (x *Stat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stat) GetBotID() string {
	if x != nil {
		return x.BotID
	}
	return ""
}

func (x *Stat) GetBotUsername() string {
	if x != nil {
		return x.BotUsername
	}
	return ""
}

func (x *Stat) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *Stat) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

func (x *Stat) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type StartBroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotIDs   []string  `protobuf:"bytes,1,rep,name=botIDs,proto3" json:"botIDs,omitempty"`
	Type     string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	FileLink string    `protobuf:"bytes,3,opt,name=fileLink,proto3" json:"fileLink,omitempty"`
	Buttons  []*Button `protobuf:"bytes,4,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Text     string    `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	ChatID   int64     `protobuf:"varint,6,opt,name=chatID,proto3" json:"chatID,omitempty"`
}

func (x *StartBroadcastRequest) Reset() {
	*x = StartBroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBroadcastRequest) ProtoMessage() {}

func (x *StartBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBroadcastRequest.ProtoReflect.Descriptor instead.
func (*StartBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{7}
}

func (x *StartBroadcastRequest) GetBotIDs() []string {
	if x != nil {
		return x.BotIDs
	}
	return nil
}

func (x *StartBroadcastRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StartBroadcastRequest) GetFileLink() string {
	if x != nil {
		return x.FileLink
	}
	return ""
}

func (x *StartBroadcastRequest) GetButtons() []*Button {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *StartBroadcastRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StartBroadcastRequest) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

type Button struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Button) Reset() {
	*x = Button{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Button) ProtoMessage() {}

func (x *Button) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Button.ProtoReflect.Descriptor instead.
func (*Button) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{8}
}

func (x *Button) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Button) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type StartBroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartBroadcastResponse) Reset() {
	*x = StartBroadcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBroadcastResponse) ProtoMessage() {}

func (x *StartBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBroadcastResponse.ProtoReflect.Descriptor instead.
func (*StartBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{9}
}

type HardCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *HardCheckRequest) Reset() {
	*x = HardCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HardCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardCheckRequest) ProtoMessage() {}

func (x *HardCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardCheckRequest.ProtoReflect.Descriptor instead.
func (*HardCheckRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{10}
}

func (x *HardCheckRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status   Status `protobuf:"varint,3,opt,name=status,proto3,enum=protobuf.Status" json:"status,omitempty"`
}

func (x *Check) Reset() {
	*x = Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{11}
}

func (x *Check) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Check) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Check) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

//----------------------------------------------------------------------------------------------------------------------
//  Change All Bonus Active
//----------------------------------------------------------------------------------------------------------------------
type ChangeBonusActiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChangeBonusActiveRequest) Reset() {
	*x = ChangeBonusActiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBonusActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBonusActiveRequest) ProtoMessage() {}

func (x *ChangeBonusActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBonusActiveRequest.ProtoReflect.Descriptor instead.
func (*ChangeBonusActiveRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeBonusActiveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ChangeBonusActiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeBonusActiveResponse) Reset() {
	*x = ChangeBonusActiveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBonusActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBonusActiveResponse) ProtoMessage() {}

func (x *ChangeBonusActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBonusActiveResponse.ProtoReflect.Descriptor instead.
func (*ChangeBonusActiveResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{13}
}

//----------------------------------------------------------------------------------------------------------------------
//  Get All Users Count
//----------------------------------------------------------------------------------------------------------------------
type GetAllUsersCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllUsersCountRequest) Reset() {
	*x = GetAllUsersCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUsersCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersCountRequest) ProtoMessage() {}

func (x *GetAllUsersCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersCountRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersCountRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{14}
}

type GetAllUsersCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counts []*Counts `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
}

func (x *GetAllUsersCountResponse) Reset() {
	*x = GetAllUsersCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllUsersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersCountResponse) ProtoMessage() {}

func (x *GetAllUsersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersCountResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersCountResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllUsersCountResponse) GetCounts() []*Counts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type Counts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Old      *Count `protobuf:"bytes,3,opt,name=old,proto3" json:"old,omitempty"`
	New      *Count `protobuf:"bytes,4,opt,name=new,proto3" json:"new,omitempty"`
	Current  int64  `protobuf:"varint,5,opt,name=current,proto3" json:"current,omitempty"`
}

func (x *Counts) Reset() {
	*x = Counts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Counts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counts) ProtoMessage() {}

func (x *Counts) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counts.ProtoReflect.Descriptor instead.
func (*Counts) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{16}
}

func (x *Counts) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Counts) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Counts) GetOld() *Count {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *Counts) GetNew() *Count {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *Counts) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type Count struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All     int64 `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Blocked int64 `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`
}

func (x *Count) Reset() {
	*x = Count{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{17}
}

func (x *Count) GetAll() int64 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *Count) GetBlocked() int64 {
	if x != nil {
		return x.Blocked
	}
	return 0
}

//----------------------------------------------------------------------------------------------------------------------
//  Get All Servers
//----------------------------------------------------------------------------------------------------------------------
type GetListServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListServersRequest) Reset() {
	*x = GetListServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListServersRequest) ProtoMessage() {}

func (x *GetListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListServersRequest.ProtoReflect.Descriptor instead.
func (*GetListServersRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{18}
}

type GetListServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *GetListServersResponse) Reset() {
	*x = GetListServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListServersResponse) ProtoMessage() {}

func (x *GetListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListServersResponse.ProtoReflect.Descriptor instead.
func (*GetListServersResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{19}
}

func (x *GetListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

//----------------------------------------------------------------------------------------------------------------------
//  Get Server
//----------------------------------------------------------------------------------------------------------------------
type GetServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{20}
}

func (x *GetServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *GetServerResponse) Reset() {
	*x = GetServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerResponse) ProtoMessage() {}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerResponse.ProtoReflect.Descriptor instead.
func (*GetServerResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{21}
}

func (x *GetServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

//----------------------------------------------------------------------------------------------------------------------
//  Init box
//----------------------------------------------------------------------------------------------------------------------
type InitBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *InitBoxRequest) Reset() {
	*x = InitBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBoxRequest) ProtoMessage() {}

func (x *InitBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBoxRequest.ProtoReflect.Descriptor instead.
func (*InitBoxRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{22}
}

func (x *InitBoxRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InitBoxRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *InitBoxRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type InitBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *InitBoxResponse) Reset() {
	*x = InitBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitBoxResponse) ProtoMessage() {}

func (x *InitBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitBoxResponse.ProtoReflect.Descriptor instead.
func (*InitBoxResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{23}
}

func (x *InitBoxResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

//----------------------------------------------------------------------------------------------------------------------
//  Send Error
//----------------------------------------------------------------------------------------------------------------------
type SendErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=protobuf.Status" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *SendErrorRequest) Reset() {
	*x = SendErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendErrorRequest) ProtoMessage() {}

func (x *SendErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendErrorRequest.ProtoReflect.Descriptor instead.
func (*SendErrorRequest) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{24}
}

func (x *SendErrorRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *SendErrorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendErrorResponse) Reset() {
	*x = SendErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendErrorResponse) ProtoMessage() {}

func (x *SendErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendErrorResponse.ProtoReflect.Descriptor instead.
func (*SendErrorResponse) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{25}
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status   string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IsActive bool   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Bonus    *Bonus `protobuf:"bytes,5,opt,name=bonus,proto3" json:"bonus,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{26}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Server) GetBonus() *Bonus {
	if x != nil {
		return x.Bonus
	}
	return nil
}

type Bonus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsActive bool  `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Cost     int64 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Time     int64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Bonus) Reset() {
	*x = Bonus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_core_protobuf_servers_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bonus) ProtoMessage() {}

func (x *Bonus) ProtoReflect() protoreflect.Message {
	mi := &file_services_core_protobuf_servers_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bonus.ProtoReflect.Descriptor instead.
func (*Bonus) Descriptor() ([]byte, []int) {
	return file_services_core_protobuf_servers_proto_rawDescGZIP(), []int{27}
}

func (x *Bonus) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Bonus) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Bonus) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_services_core_protobuf_servers_proto protoreflect.FileDescriptor

var file_services_core_protobuf_servers_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x41, 0x0a,
	0x1d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x44,
	0x22, 0x46, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x38, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x49, 0x44, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x04,
	0x53, 0x74, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6f,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x62, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0xb7,
	0x01, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x49,
	0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x2a, 0x0a, 0x07, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x75, 0x74,
	0x74, 0x6f, 0x6e, 0x52, 0x07, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x06, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2a, 0x0a, 0x10, 0x48, 0x61, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5d,
	0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a,
	0x18, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52,
	0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x03, 0x6f, 0x6c,
	0x64, 0x12, 0x21, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x03, 0x6e, 0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x33,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x49,
	0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x52,
	0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x05, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x74, 0x61,
	0x6c, 0x10, 0x02, 0x32, 0xa4, 0x07, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12,
	0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x48,
	0x61, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x07, 0x49, 0x6e, 0x69,
	0x74, 0x42, 0x6f, 0x78, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x42, 0x6f,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x53,
	0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x55, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_core_protobuf_servers_proto_rawDescOnce sync.Once
	file_services_core_protobuf_servers_proto_rawDescData = file_services_core_protobuf_servers_proto_rawDesc
)

func file_services_core_protobuf_servers_proto_rawDescGZIP() []byte {
	file_services_core_protobuf_servers_proto_rawDescOnce.Do(func() {
		file_services_core_protobuf_servers_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_core_protobuf_servers_proto_rawDescData)
	})
	return file_services_core_protobuf_servers_proto_rawDescData
}

var file_services_core_protobuf_servers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_core_protobuf_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_services_core_protobuf_servers_proto_goTypes = []interface{}{
	(Status)(0),                            // 0: protobuf.Status
	(*GetAllBroadcastsRequest)(nil),        // 1: protobuf.GetAllBroadcastsRequest
	(*GetAllBroadcastsResponse)(nil),       // 2: protobuf.GetAllBroadcastsResponse
	(*GetStatisticsBroadcastRequest)(nil),  // 3: protobuf.GetStatisticsBroadcastRequest
	(*GetStatisticsBroadcastResponse)(nil), // 4: protobuf.GetStatisticsBroadcastResponse
	(*StopBroadcastRequest)(nil),           // 5: protobuf.StopBroadcastRequest
	(*StopBroadcastResponse)(nil),          // 6: protobuf.StopBroadcastResponse
	(*Stat)(nil),                           // 7: protobuf.Stat
	(*StartBroadcastRequest)(nil),          // 8: protobuf.StartBroadcastRequest
	(*Button)(nil),                         // 9: protobuf.Button
	(*StartBroadcastResponse)(nil),         // 10: protobuf.StartBroadcastResponse
	(*HardCheckRequest)(nil),               // 11: protobuf.HardCheckRequest
	(*Check)(nil),                          // 12: protobuf.Check
	(*ChangeBonusActiveRequest)(nil),       // 13: protobuf.ChangeBonusActiveRequest
	(*ChangeBonusActiveResponse)(nil),      // 14: protobuf.ChangeBonusActiveResponse
	(*GetAllUsersCountRequest)(nil),        // 15: protobuf.GetAllUsersCountRequest
	(*GetAllUsersCountResponse)(nil),       // 16: protobuf.GetAllUsersCountResponse
	(*Counts)(nil),                         // 17: protobuf.Counts
	(*Count)(nil),                          // 18: protobuf.Count
	(*GetListServersRequest)(nil),          // 19: protobuf.GetListServersRequest
	(*GetListServersResponse)(nil),         // 20: protobuf.GetListServersResponse
	(*GetServerRequest)(nil),               // 21: protobuf.GetServerRequest
	(*GetServerResponse)(nil),              // 22: protobuf.GetServerResponse
	(*InitBoxRequest)(nil),                 // 23: protobuf.InitBoxRequest
	(*InitBoxResponse)(nil),                // 24: protobuf.InitBoxResponse
	(*SendErrorRequest)(nil),               // 25: protobuf.SendErrorRequest
	(*SendErrorResponse)(nil),              // 26: protobuf.SendErrorResponse
	(*Server)(nil),                         // 27: protobuf.Server
	(*Bonus)(nil),                          // 28: protobuf.Bonus
}
var file_services_core_protobuf_servers_proto_depIdxs = []int32{
	7,  // 0: protobuf.GetAllBroadcastsResponse.stats:type_name -> protobuf.Stat
	7,  // 1: protobuf.GetStatisticsBroadcastResponse.stats:type_name -> protobuf.Stat
	9,  // 2: protobuf.StartBroadcastRequest.buttons:type_name -> protobuf.Button
	0,  // 3: protobuf.Check.status:type_name -> protobuf.Status
	17, // 4: protobuf.GetAllUsersCountResponse.counts:type_name -> protobuf.Counts
	18, // 5: protobuf.Counts.old:type_name -> protobuf.Count
	18, // 6: protobuf.Counts.new:type_name -> protobuf.Count
	27, // 7: protobuf.GetListServersResponse.servers:type_name -> protobuf.Server
	27, // 8: protobuf.GetServerResponse.server:type_name -> protobuf.Server
	0,  // 9: protobuf.SendErrorRequest.status:type_name -> protobuf.Status
	28, // 10: protobuf.Server.bonus:type_name -> protobuf.Bonus
	19, // 11: protobuf.Servers.GetListServers:input_type -> protobuf.GetListServersRequest
	21, // 12: protobuf.Servers.GetServer:input_type -> protobuf.GetServerRequest
	15, // 13: protobuf.Servers.GetAllUsersCount:input_type -> protobuf.GetAllUsersCountRequest
	13, // 14: protobuf.Servers.ChangeBonusActive:input_type -> protobuf.ChangeBonusActiveRequest
	11, // 15: protobuf.Servers.HardCheck:input_type -> protobuf.HardCheckRequest
	23, // 16: protobuf.Servers.InitBox:input_type -> protobuf.InitBoxRequest
	25, // 17: protobuf.Servers.SendError:input_type -> protobuf.SendErrorRequest
	1,  // 18: protobuf.Servers.GetAllBroadcasts:input_type -> protobuf.GetAllBroadcastsRequest
	8,  // 19: protobuf.Servers.StartBroadcast:input_type -> protobuf.StartBroadcastRequest
	5,  // 20: protobuf.Servers.StopBroadcast:input_type -> protobuf.StopBroadcastRequest
	3,  // 21: protobuf.Servers.GetStatisticsBroadcast:input_type -> protobuf.GetStatisticsBroadcastRequest
	20, // 22: protobuf.Servers.GetListServers:output_type -> protobuf.GetListServersResponse
	22, // 23: protobuf.Servers.GetServer:output_type -> protobuf.GetServerResponse
	16, // 24: protobuf.Servers.GetAllUsersCount:output_type -> protobuf.GetAllUsersCountResponse
	14, // 25: protobuf.Servers.ChangeBonusActive:output_type -> protobuf.ChangeBonusActiveResponse
	12, // 26: protobuf.Servers.HardCheck:output_type -> protobuf.Check
	24, // 27: protobuf.Servers.InitBox:output_type -> protobuf.InitBoxResponse
	26, // 28: protobuf.Servers.SendError:output_type -> protobuf.SendErrorResponse
	2,  // 29: protobuf.Servers.GetAllBroadcasts:output_type -> protobuf.GetAllBroadcastsResponse
	10, // 30: protobuf.Servers.StartBroadcast:output_type -> protobuf.StartBroadcastResponse
	6,  // 31: protobuf.Servers.StopBroadcast:output_type -> protobuf.StopBroadcastResponse
	4,  // 32: protobuf.Servers.GetStatisticsBroadcast:output_type -> protobuf.GetStatisticsBroadcastResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_services_core_protobuf_servers_proto_init() }
func file_services_core_protobuf_servers_proto_init() {
	if File_services_core_protobuf_servers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_core_protobuf_servers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBroadcastsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBroadcastsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsBroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsBroadcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopBroadcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Button); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBroadcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HardCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBonusActiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBonusActiveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUsersCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllUsersCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Counts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Count); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_core_protobuf_servers_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bonus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_core_protobuf_servers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_core_protobuf_servers_proto_goTypes,
		DependencyIndexes: file_services_core_protobuf_servers_proto_depIdxs,
		EnumInfos:         file_services_core_protobuf_servers_proto_enumTypes,
		MessageInfos:      file_services_core_protobuf_servers_proto_msgTypes,
	}.Build()
	File_services_core_protobuf_servers_proto = out.File
	file_services_core_protobuf_servers_proto_rawDesc = nil
	file_services_core_protobuf_servers_proto_goTypes = nil
	file_services_core_protobuf_servers_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServersClient is the client API for Servers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServersClient interface {
	GetListServers(ctx context.Context, in *GetListServersRequest, opts ...grpc.CallOption) (*GetListServersResponse, error)
	GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerResponse, error)
	GetAllUsersCount(ctx context.Context, in *GetAllUsersCountRequest, opts ...grpc.CallOption) (*GetAllUsersCountResponse, error)
	ChangeBonusActive(ctx context.Context, in *ChangeBonusActiveRequest, opts ...grpc.CallOption) (*ChangeBonusActiveResponse, error)
	HardCheck(ctx context.Context, in *HardCheckRequest, opts ...grpc.CallOption) (Servers_HardCheckClient, error)
	//BOX METHODS
	InitBox(ctx context.Context, in *InitBoxRequest, opts ...grpc.CallOption) (*InitBoxResponse, error)
	SendError(ctx context.Context, in *SendErrorRequest, opts ...grpc.CallOption) (*SendErrorResponse, error)
	GetAllBroadcasts(ctx context.Context, in *GetAllBroadcastsRequest, opts ...grpc.CallOption) (*GetAllBroadcastsResponse, error)
	StartBroadcast(ctx context.Context, in *StartBroadcastRequest, opts ...grpc.CallOption) (*StartBroadcastResponse, error)
	StopBroadcast(ctx context.Context, in *StopBroadcastRequest, opts ...grpc.CallOption) (*StopBroadcastResponse, error)
	GetStatisticsBroadcast(ctx context.Context, in *GetStatisticsBroadcastRequest, opts ...grpc.CallOption) (*GetStatisticsBroadcastResponse, error)
}

type serversClient struct {
	cc grpc.ClientConnInterface
}

func NewServersClient(cc grpc.ClientConnInterface) ServersClient {
	return &serversClient{cc}
}

func (c *serversClient) GetListServers(ctx context.Context, in *GetListServersRequest, opts ...grpc.CallOption) (*GetListServersResponse, error) {
	out := new(GetListServersResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/GetListServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) GetServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerResponse, error) {
	out := new(GetServerResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/GetServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) GetAllUsersCount(ctx context.Context, in *GetAllUsersCountRequest, opts ...grpc.CallOption) (*GetAllUsersCountResponse, error) {
	out := new(GetAllUsersCountResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/GetAllUsersCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) ChangeBonusActive(ctx context.Context, in *ChangeBonusActiveRequest, opts ...grpc.CallOption) (*ChangeBonusActiveResponse, error) {
	out := new(ChangeBonusActiveResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/ChangeBonusActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) HardCheck(ctx context.Context, in *HardCheckRequest, opts ...grpc.CallOption) (Servers_HardCheckClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Servers_serviceDesc.Streams[0], "/protobuf.Servers/HardCheck", opts...)
	if err != nil {
		return nil, err
	}
	x := &serversHardCheckClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Servers_HardCheckClient interface {
	Recv() (*Check, error)
	grpc.ClientStream
}

type serversHardCheckClient struct {
	grpc.ClientStream
}

func (x *serversHardCheckClient) Recv() (*Check, error) {
	m := new(Check)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serversClient) InitBox(ctx context.Context, in *InitBoxRequest, opts ...grpc.CallOption) (*InitBoxResponse, error) {
	out := new(InitBoxResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/InitBox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) SendError(ctx context.Context, in *SendErrorRequest, opts ...grpc.CallOption) (*SendErrorResponse, error) {
	out := new(SendErrorResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/SendError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) GetAllBroadcasts(ctx context.Context, in *GetAllBroadcastsRequest, opts ...grpc.CallOption) (*GetAllBroadcastsResponse, error) {
	out := new(GetAllBroadcastsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/GetAllBroadcasts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) StartBroadcast(ctx context.Context, in *StartBroadcastRequest, opts ...grpc.CallOption) (*StartBroadcastResponse, error) {
	out := new(StartBroadcastResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/StartBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) StopBroadcast(ctx context.Context, in *StopBroadcastRequest, opts ...grpc.CallOption) (*StopBroadcastResponse, error) {
	out := new(StopBroadcastResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/StopBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serversClient) GetStatisticsBroadcast(ctx context.Context, in *GetStatisticsBroadcastRequest, opts ...grpc.CallOption) (*GetStatisticsBroadcastResponse, error) {
	out := new(GetStatisticsBroadcastResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Servers/GetStatisticsBroadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServersServer is the server API for Servers service.
type ServersServer interface {
	GetListServers(context.Context, *GetListServersRequest) (*GetListServersResponse, error)
	GetServer(context.Context, *GetServerRequest) (*GetServerResponse, error)
	GetAllUsersCount(context.Context, *GetAllUsersCountRequest) (*GetAllUsersCountResponse, error)
	ChangeBonusActive(context.Context, *ChangeBonusActiveRequest) (*ChangeBonusActiveResponse, error)
	HardCheck(*HardCheckRequest, Servers_HardCheckServer) error
	//BOX METHODS
	InitBox(context.Context, *InitBoxRequest) (*InitBoxResponse, error)
	SendError(context.Context, *SendErrorRequest) (*SendErrorResponse, error)
	GetAllBroadcasts(context.Context, *GetAllBroadcastsRequest) (*GetAllBroadcastsResponse, error)
	StartBroadcast(context.Context, *StartBroadcastRequest) (*StartBroadcastResponse, error)
	StopBroadcast(context.Context, *StopBroadcastRequest) (*StopBroadcastResponse, error)
	GetStatisticsBroadcast(context.Context, *GetStatisticsBroadcastRequest) (*GetStatisticsBroadcastResponse, error)
}

// UnimplementedServersServer can be embedded to have forward compatible implementations.
type UnimplementedServersServer struct {
}

func (*UnimplementedServersServer) GetListServers(context.Context, *GetListServersRequest) (*GetListServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListServers not implemented")
}
func (*UnimplementedServersServer) GetServer(context.Context, *GetServerRequest) (*GetServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServer not implemented")
}
func (*UnimplementedServersServer) GetAllUsersCount(context.Context, *GetAllUsersCountRequest) (*GetAllUsersCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsersCount not implemented")
}
func (*UnimplementedServersServer) ChangeBonusActive(context.Context, *ChangeBonusActiveRequest) (*ChangeBonusActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeBonusActive not implemented")
}
func (*UnimplementedServersServer) HardCheck(*HardCheckRequest, Servers_HardCheckServer) error {
	return status.Errorf(codes.Unimplemented, "method HardCheck not implemented")
}
func (*UnimplementedServersServer) InitBox(context.Context, *InitBoxRequest) (*InitBoxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBox not implemented")
}
func (*UnimplementedServersServer) SendError(context.Context, *SendErrorRequest) (*SendErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendError not implemented")
}
func (*UnimplementedServersServer) GetAllBroadcasts(context.Context, *GetAllBroadcastsRequest) (*GetAllBroadcastsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBroadcasts not implemented")
}
func (*UnimplementedServersServer) StartBroadcast(context.Context, *StartBroadcastRequest) (*StartBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBroadcast not implemented")
}
func (*UnimplementedServersServer) StopBroadcast(context.Context, *StopBroadcastRequest) (*StopBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopBroadcast not implemented")
}
func (*UnimplementedServersServer) GetStatisticsBroadcast(context.Context, *GetStatisticsBroadcastRequest) (*GetStatisticsBroadcastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatisticsBroadcast not implemented")
}

func RegisterServersServer(s *grpc.Server, srv ServersServer) {
	s.RegisterService(&_Servers_serviceDesc, srv)
}

func _Servers_GetListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).GetListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/GetListServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).GetListServers(ctx, req.(*GetListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_GetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).GetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/GetServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).GetServer(ctx, req.(*GetServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_GetAllUsersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).GetAllUsersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/GetAllUsersCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).GetAllUsersCount(ctx, req.(*GetAllUsersCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_ChangeBonusActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeBonusActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).ChangeBonusActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/ChangeBonusActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).ChangeBonusActive(ctx, req.(*ChangeBonusActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_HardCheck_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HardCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServersServer).HardCheck(m, &serversHardCheckServer{stream})
}

type Servers_HardCheckServer interface {
	Send(*Check) error
	grpc.ServerStream
}

type serversHardCheckServer struct {
	grpc.ServerStream
}

func (x *serversHardCheckServer) Send(m *Check) error {
	return x.ServerStream.SendMsg(m)
}

func _Servers_InitBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).InitBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/InitBox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).InitBox(ctx, req.(*InitBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_SendError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).SendError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/SendError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).SendError(ctx, req.(*SendErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_GetAllBroadcasts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBroadcastsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).GetAllBroadcasts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/GetAllBroadcasts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).GetAllBroadcasts(ctx, req.(*GetAllBroadcastsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_StartBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).StartBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/StartBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).StartBroadcast(ctx, req.(*StartBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_StopBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).StopBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/StopBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).StopBroadcast(ctx, req.(*StopBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servers_GetStatisticsBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServersServer).GetStatisticsBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Servers/GetStatisticsBroadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServersServer).GetStatisticsBroadcast(ctx, req.(*GetStatisticsBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Servers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Servers",
	HandlerType: (*ServersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListServers",
			Handler:    _Servers_GetListServers_Handler,
		},
		{
			MethodName: "GetServer",
			Handler:    _Servers_GetServer_Handler,
		},
		{
			MethodName: "GetAllUsersCount",
			Handler:    _Servers_GetAllUsersCount_Handler,
		},
		{
			MethodName: "ChangeBonusActive",
			Handler:    _Servers_ChangeBonusActive_Handler,
		},
		{
			MethodName: "InitBox",
			Handler:    _Servers_InitBox_Handler,
		},
		{
			MethodName: "SendError",
			Handler:    _Servers_SendError_Handler,
		},
		{
			MethodName: "GetAllBroadcasts",
			Handler:    _Servers_GetAllBroadcasts_Handler,
		},
		{
			MethodName: "StartBroadcast",
			Handler:    _Servers_StartBroadcast_Handler,
		},
		{
			MethodName: "StopBroadcast",
			Handler:    _Servers_StopBroadcast_Handler,
		},
		{
			MethodName: "GetStatisticsBroadcast",
			Handler:    _Servers_GetStatisticsBroadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HardCheck",
			Handler:       _Servers_HardCheck_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/core/protobuf/servers.proto",
}
